// Constants/chapterConstants.js
export const CREATE_CHAPTER_REQUEST = "CREATE_CHAPTER_REQUEST";
export const CREATE_CHAPTER_SUCCESS = "CREATE_CHAPTER_SUCCESS";
export const CREATE_CHAPTER_FAIL = "CREATE_CHAPTER_FAIL";

export const GET_CHAPTERS_REQUEST = "GET_CHAPTERS_REQUEST";
export const GET_CHAPTERS_SUCCESS = "GET_CHAPTERS_SUCCESS";
export const GET_CHAPTERS_FAIL = "GET_CHAPTERS_FAIL";

export const GET_CHAPTER_REQUEST = "GET_CHAPTER_REQUEST";
export const GET_CHAPTER_SUCCESS = "GET_CHAPTER_SUCCESS";
export const GET_CHAPTER_FAIL = "GET_CHAPTER_FAIL";
